spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password: 
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080

resource: src/main/resources/static/cidades.csv